// <auto-generated />
namespace Obligatorio2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changesinimports : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesinimports));
        
        string IMigrationMetadata.Id
        {
            get { return "202007011815357_changes-in-imports"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
